version: '-0.0.0.{build}'
image: Visual Studio 2019

environment:
  TITLE: 'YDL-UI'
  PROJECT_NAME: 'YDL-UI'
  ISS: 'ydl-ui-installer.iss'

skip_commits:
  files:
    - README.md
branches:
  only:
    - 'dev/v3'

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(APP_VERSION)'
  assembly_file_version: '$(APP_VERSION)'
  assembly_informational_version: '$(APP_VERSION_INFORMATIONAL)'

before_build:
  - nuget restore

install:
  - ps: ./update-version-v2.ps1

build:
  project: '$(PROJECT_NAME).sln'
  verbosity: minimal

after_build:
  - ps: ./package-build.ps1

artifacts:
  - path: '$(TITLE)-Portable_v*.zip'
    name: $(CONFIGURATION)-Portable
  - path: '$(TITLE)-Setup_v*.exe'
    name: $(CONFIGURATION)-Setup


test: off
deploy: off