version: '3.0.0.{build}'
image: Visual Studio 2019

environment:
  TITLE: 'YDL-UI'
  PROJECT_NAME: 'YDL-UI'

skip_commits:
  files:
    - README.md
branches:
  only:
    - 'dev/v3'

configuration:
  - Debug
  - Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-dev'

before_build:
  - nuget restore

build:
  project: '$(PROJECT_NAME).sln'
  verbosity: minimal

test: off
deploy: off